//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlaBlaRunProject.Domain.Concrete
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EFDBContextContainer : DbContext
    {
        public EFDBContextContainer()
            : base("name=EFDBContextContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Workouts> WorkoutsSet { get; set; }
        public virtual DbSet<Users> UsersSet { get; set; }
        public virtual DbSet<WorkoutsOld> WorkoutsOldSet { get; set; }
        public virtual DbSet<Audit> AuditSet { get; set; }
    }
}
